theme: jekyll-theme-minimal
title: Legal Documents
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-optional-front-matter # Processes markdown files without front matter
defaults:
  -
    scope:
      path: "" # Apply to all files
    values:
      layout: default # Use the default layout for all files
